### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML Skeleton
- [x] Create styles.css and main.js
- [x] Link CSS and JS to HTML 
- [x] Create car and driving surface in HTML
- [x] Style car and driving surface
- [x] Fix any errors
