### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model with direction property
- [x] Create handle function that turns the car and updates direction property
- [x] Add keydown event listener to document
- [x] Fix all errors
