### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Absolutely position car
- [x] Add x and y coordinates to data model
- [x] Add functionality to move car forward continuously 
- [ ] Fix all errors
